name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to upload files to the GitHub release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21   # use 17 for MC 1.18-1.20.4, 21 for 1.20.5+

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: mc-publish
        uses: Kira-NT/mc-publish@v3.3.1
        with:
          modrinth-id: iQ3RruEb
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1724905
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/!(*-@(dev|sources|javadoc)).jar
